# Documentation: http://docs.travis-ci.com/user/languages/julia/
language: julia
os:
  - linux
julia:
  - 0.6
notifications:
  email: false
script:
  - if [[ -a .git/shallow ]]; then git fetch --unshallow; fi
  - julia -e 'Pkg.clone(pwd()); Pkg.build("TravisTest")'
  - julia -e 'Pkg.test("TravisTest")'
after_success:
# update the documentation
  - julia -e 'Pkg.add("Documenter")'
  - julia -e 'cd(Pkg.dir("TravisTest")); ENV["DOCUMENTER_DEBUG"] = "true"; include(joinpath("docs", "make.jl"))'